import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Image from "next/image"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#1A1A2E] text-white">
      {/* Header */}
      <header className="border-b border-gray-800 bg-[#1A1A2E]/95 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <Link href="/">
              <Button variant="ghost" size="sm">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>
            <Image src="/logo.png" alt="Trollify" width={100} height={32} className="h-8 w-auto" />
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Card className="bg-gray-900/50 border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl text-[#00DDEB]">Terms of Service</CardTitle>
            <p className="text-gray-400">Last updated: {new Date().toLocaleDateString()}</p>
          </CardHeader>
          <CardContent className="prose prose-invert max-w-none">
            <div className="space-y-6 text-gray-300">
              <section>
                <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                <p>
                  By accessing and using Trollify ("the Service"), you accept and agree to be bound by the terms and
                  provision of this agreement. If you do not agree to abide by the above, please do not use this
                  service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">2. Purpose and Intended Use</h2>
                <p>
                  Trollify is designed exclusively for entertainment, educational, and testing purposes. The Service
                  allows users to create fictional social media content that mimics the appearance of real platforms.
                </p>
                <p className="mt-2">
                  <strong className="text-red-400">All content generated by this service is fake and fictional.</strong>
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">3. Prohibited Uses</h2>
                <p>You agree NOT to use the Service for:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>Fraud, deception, or misrepresentation</li>
                  <li>Defamation, harassment, or cyberbullying</li>
                  <li>Impersonation of real individuals without consent</li>
                  <li>Creating content that could cause harm or distress</li>
                  <li>Any illegal activities or purposes</li>
                  <li>Spreading misinformation or fake news</li>
                  <li>Commercial use without explicit permission</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">4. User Responsibilities</h2>
                <p>Users are solely responsible for:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>The content they create using the Service</li>
                  <li>Ensuring their use complies with applicable laws</li>
                  <li>Respecting the rights and privacy of others</li>
                  <li>Adding appropriate disclaimers when sharing generated content</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
                <p>
                  The Service does not claim ownership of user-generated content. However, users must ensure they have
                  the right to use any images, text, or other materials they upload to the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">6. Disclaimer of Warranties</h2>
                <p>
                  The Service is provided "as is" without any warranties, expressed or implied. We do not guarantee the
                  accuracy, reliability, or availability of the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">7. Limitation of Liability</h2>
                <p>
                  Neontek and Trollify shall not be liable for any direct, indirect, incidental, special, consequential,
                  or punitive damages resulting from your use of the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">8. Termination</h2>
                <p>
                  We reserve the right to terminate or suspend access to the Service immediately, without prior notice,
                  for any reason, including breach of these Terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">9. Changes to Terms</h2>
                <p>
                  We reserve the right to modify these terms at any time. Changes will be effective immediately upon
                  posting to the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">10. Contact Information</h2>
                <p>For questions about these Terms of Service, please contact us through our official channels.</p>
              </section>

              <div className="bg-red-900/20 border border-red-800/30 rounded-lg p-4 mt-8">
                <h3 className="text-lg font-semibold text-red-400 mb-2">⚠️ Important Reminder</h3>
                <p className="text-sm">
                  By using Trollify, you acknowledge that all generated content is fictional and agree to use the
                  Service responsibly and ethically. Misuse of this service may result in legal consequences.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
